services:
  #
  # Managers
  #

  eos.manager.user_info:
    class: EosBundle\Manager\UserInfoManager
    arguments:
      - '@doctrine_mongodb'
      - 'EosBundle\Document\UserInfo'
    calls:
      - [ setRepository, ['@eos.repository.user_info'] ]

  eos.manager.usage:
    class: EosBundle\Manager\UsageManager
    arguments:
      - '@doctrine_mongodb'
      - 'EosBundle\Document\Usage'
    calls:
      - [ setRepository, ['@eos.repository.usage'] ]

  eos.manager.luna_exception:
    class: EosBundle\Manager\LunaExceptionManager
    arguments:
      - '@doctrine_mongodb'
      - 'EosBundle\Document\LunaException'
    calls:
      - [ setRepository, ['@eos.repository.luna_exception'] ]

  eos.manager.luna_log_entry:
    class: EosBundle\Manager\LunaLogEntryManager
    arguments:
      - '@doctrine_mongodb'
      - 'EosBundle\Document\LunaLogEntry'
    calls:
      - [ setRepository, ['@eos.repository.luna_log_entry'] ]

  eos.manager.luna_uuid:
    class: EosBundle\Manager\LunaUuidManager
    arguments:
      - '@doctrine_mongodb'
      - 'EosBundle\Document\LunaUuid'
    calls:
      - [ setRepository, ['@eos.repository.luna_uuid'] ]


  #
  # Repositories
  #

  eos.repository.user_info:
    class: Doctrine\Common\Persistence\ObjectRepository
    factory:
      - '@doctrine_mongodb'
      - getRepository
    arguments:
      - 'EosBundle\Document\UserInfo'

  eos.repository.usage:
    class: Doctrine\Common\Persistence\ObjectRepository
    factory:
      - '@doctrine_mongodb'
      - getRepository
    arguments:
      - 'EosBundle\Document\Usage'

  eos.repository.luna_exception:
    class: Doctrine\Common\Persistence\ObjectRepository
    factory:
      - '@doctrine_mongodb'
      - getRepository
    arguments:
      - 'EosBundle\Document\LunaException'

  eos.repository.luna_log_entry:
    class: Doctrine\Common\Persistence\ObjectRepository
    factory:
      - '@doctrine_mongodb'
      - getRepository
    arguments:
      - 'EosBundle\Document\LunaLogEntry'

  eos.repository.luna_uuid:
    class: Doctrine\Common\Persistence\ObjectRepository
    factory:
      - '@doctrine_mongodb'
      - getRepository
    arguments:
      - 'EosBundle\Document\LunaUuid'


  #
  # ParamConverter
  #

  eos.param_converter.user:
    class: EosBundle\Request\ParamConverter\UserParamConverter
    arguments:
      - '@eos.manager.user_info'
      - '@eos.manager.luna_uuid'
      - 'EosBundle\Document\UserInfo'
    tags:
      - { name: request.param_converter, alias: UserParamConverter }
